{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"financials\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.138.1452.0 (24.11)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "financials": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "financials": {
                      "State": "Generated"
                    }
                  },
                  {
                    "financials": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  }
                ]
              },
              "financials.cog": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "COGS"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cog": {
                      "State": "Generated"
                    }
                  },
                  {
                    "cog": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "mechanism": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "cogwheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "gearwheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "flywheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "component": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "gear": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "wheel": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "financials.country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "country": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "financials.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "hierarquia de data": {
                      "State": "Generated"
                    }
                  },
                  {
                    "hierarquia de data": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "hierarquia de information": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de fact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de info": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de statistic": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "hierarquia de document": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de figure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "hierarquia de record": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Ano",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ano": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date ano": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date ano": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period ano": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.dia": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Dia",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "dia": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date dia": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date dia": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period dia": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.mê": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Mês",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mê": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date mê": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date mê": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period mê": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.date.variation.hierarquia_de_data.trimestre": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "Hierarchy": "Hierarquia de datas",
                    "HierarchyLevel": "Trimestre",
                    "VariationSet": "Variation",
                    "VariationSource": "Date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "trimestre": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "date trimestre": {
                      "State": "Generated"
                    }
                  },
                  {
                    "date trimestre": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "moment trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  },
                  {
                    "period trimestre": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "financials.discount": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Discounts"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "discount": {
                      "State": "Generated"
                    }
                  },
                  {
                    "discount": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "reduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "markdown": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "concession": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "deduction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "rebate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "financials.discount_band": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Discount Band"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "discount band": {
                      "State": "Generated"
                    }
                  },
                  {
                    "discount band": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "band": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "band": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "discount posse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "posse": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "discount group": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount gang": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount crew": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount crowd": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "discount mob": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "gang": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crew": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "crowd": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "financials.gross_sale": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Gross Sales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "gross sale": {
                      "State": "Generated"
                    }
                  },
                  {
                    "gross sale": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "aggregate sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.647
                    }
                  },
                  {
                    "overall sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.647
                    }
                  },
                  {
                    "whole sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.647
                    }
                  },
                  {
                    "sum sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total sale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "gross auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "gross transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "gross deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "gross trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "gross vending": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  }
                ]
              },
              "financials.manufacturing_price": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Manufacturing Price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "manufacturing price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "manufacturing price": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "manufacturing value": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing fee": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "manufacturing outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "financials.month_name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Month Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month name": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month nickname": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "month tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth name": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "financials.month_number": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Month Number"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month number": {
                      "State": "Generated"
                    }
                  },
                  {
                    "month number": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "month no": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "mth number": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.6
                    }
                  }
                ]
              },
              "financials.product": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Product"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "product": {
                      "State": "Generated"
                    }
                  },
                  {
                    "product": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "artifact": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "item": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "merchandise": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "produce": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "financials.profit": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Profit"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "profit": {
                      "State": "Generated"
                    }
                  },
                  {
                    "profit": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "revenue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "return": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "advantage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "gain": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "benefit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "use": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "reward": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "financials.sale": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": " Sales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sale": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    " Sales": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "Sales": {
                      "State": "Generated",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "Sales": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.96029999999999993
                    }
                  },
                  {
                    "auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "vending": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "retailing": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  },
                  {
                    "selling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "financials.sale_price": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Sale Price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "sale price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "sale price": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "price": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.97
                    }
                  },
                  {
                    "sale value": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale fee": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "sale outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "financials.segment": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Segment"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "segment": {
                      "State": "Generated"
                    }
                  },
                  {
                    "segment": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "division": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "subdivision": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "section": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "sector": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "bit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "fragment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "part": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "piece": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "portion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "slice": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "financials.unit_sold": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Units Sold"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "unit sold": {
                      "State": "Generated"
                    }
                  },
                  {
                    "unit sold": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "module sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "element sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "entity sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "group sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "component sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "constituent sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "item sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "part sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "section sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "financials.year": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "financials",
                    "ConceptualProperty": "Year"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "year": {
                      "State": "Generated"
                    }
                  },
                  {
                    "year": {
                      "State": "Generated",
                      "Type": "Noun"
                    }
                  },
                  {
                    "yr": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "financials_date_has_variation_hierarquia_de_data": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      },
                      "Subject": {
                        "Role": "financials.date"
                      }
                    },
                    "ID": "dates_have_hierarquia_de_data",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date": {
                    "Target": {
                      "Entity": "financials.date"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_ano_has_financials_date_variation_hierarquia_de_data_trimestre": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      }
                    },
                    "ID": "anos_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      }
                    },
                    "ID": "trimestres_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "trimestres_are_in_anos",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data.ano": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.ano"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.trimestre": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_ano": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.ano"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.ano": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_dia": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.dia": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.dia"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_mê": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.mê": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_has_trimestre": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data"
                      }
                    },
                    "ID": "hierarquia_de_data_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.trimestre": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_mê_has_financials_date_variation_hierarquia_de_data_dia": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      }
                    },
                    "ID": "mê_have_dias",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      }
                    },
                    "ID": "dias_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "dias_are_in_mê",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.dia"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data.dia": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.dia"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.mê": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.mê"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_date_variation_hierarquia_de_data_trimestre_has_financials_date_variation_hierarquia_de_data_mê": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      }
                    },
                    "ID": "trimestres_have_mê",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      }
                    },
                    "ID": "mê_have_trimestres",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "mê_are_in_trimestres",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.date.variation.hierarquia_de_data.trimestre"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials.date.variation.hierarquia_de_data.mê"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials.date.variation.hierarquia_de_data.mê": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.mê"
                    }
                  },
                  "financials.date.variation.hierarquia_de_data.trimestre": {
                    "Target": {
                      "Entity": "financials.date.variation.hierarquia_de_data.trimestre"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_cog": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.cog"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_cogs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.cog": {
                    "Target": {
                      "Entity": "financials.cog"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_country": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.country"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.country": {
                    "Target": {
                      "Entity": "financials.country"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_date": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.date"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.date": {
                    "Target": {
                      "Entity": "financials.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_discount": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.discount"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_discounts",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.discount": {
                    "Target": {
                      "Entity": "financials.discount"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_discount_band": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.discount_band"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_discount_bands",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.discount_band": {
                    "Target": {
                      "Entity": "financials.discount_band"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_gross_sale": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.gross_sale"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_gross_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.gross_sale": {
                    "Target": {
                      "Entity": "financials.gross_sale"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_manufacturing_price": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.manufacturing_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_manufacturing_prices",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "financials.manufacturing_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "manufacturing_price_indicates_how_expensive_financials_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.manufacturing_price": {
                    "Target": {
                      "Entity": "financials.manufacturing_price"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_month_name": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.month_name"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_month_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.month_name": {
                    "Target": {
                      "Entity": "financials.month_name"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_month_number": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.month_number"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_month_numbers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.month_number": {
                    "Target": {
                      "Entity": "financials.month_number"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_product": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.product"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_products",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.product": {
                    "Target": {
                      "Entity": "financials.product"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_profit": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.profit"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_profits",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.profit": {
                    "Target": {
                      "Entity": "financials.profit"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_sale": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.sale"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.sale": {
                    "Target": {
                      "Entity": "financials.sale"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_sale_price": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.sale_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_sale_prices",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "financials.sale_price"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "sale_price_indicates_how_expensive_financials_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.sale_price": {
                    "Target": {
                      "Entity": "financials.sale_price"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_segment": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.segment"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_segments",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.segment": {
                    "Target": {
                      "Entity": "financials.segment"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_unit_sold": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.unit_sold"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_unit_sold",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.unit_sold": {
                    "Target": {
                      "Entity": "financials.unit_sold"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_has_year": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "financials.year"
                      },
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "ID": "financials_have_years",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.year": {
                    "Target": {
                      "Entity": "financials.year"
                    }
                  }
                },
                "State": "Generated"
              },
              "financials_in_country": {
                "Binding": {
                  "ConceptualEntity": "financials"
                },
                "Phrasings": [
                  {
                    "ID": "financials_are_in_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "financials.country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "financials"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "financials": {
                    "Target": {
                      "Entity": "financials"
                    }
                  },
                  "financials.country": {
                    "Target": {
                      "Entity": "financials.country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "financials.country"
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "dd1b9b21-4398-475b-a672-8423a7b1d115",
        "fromColumn": "Date",
        "fromTable": "financials",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c3011088-7384-4d5c-b202-ab45b52fa449"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "financials",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Segment",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "715048ef-4417-4b40-addd-46a052f6c70d",
            "sourceColumn": "Segment",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3037c8ab-6bf2-4a4f-8e28-225afb8fc46a",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Product",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6f4516ca-98e1-437e-b7cb-91a1880b7fbf",
            "sourceColumn": "Product",
            "summarizeBy": "none"
          },
          {
            "name": "Discount Band",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "528d9d69-ed44-49a9-83c3-6d7f1afb40de",
            "sourceColumn": "Discount Band",
            "summarizeBy": "none"
          },
          {
            "name": "Units Sold",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5de56f8d-6087-4c5a-903e-9a8a1cf6ca2e",
            "sourceColumn": "Units Sold",
            "summarizeBy": "sum"
          },
          {
            "name": "Manufacturing Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e830a26e-4912-4d3b-a1a7-5591bfb02c9b",
            "sourceColumn": "Manufacturing Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Sale Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "25338a30-ad8c-468f-ae30-362eca9fd96c",
            "sourceColumn": "Sale Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd2de776-28ca-49e3-9568-4db9204da2bd",
            "sourceColumn": "Gross Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "Discounts",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a9614cdc-d0d5-45de-8ec8-e877a4eb66a5",
            "sourceColumn": "Discounts",
            "summarizeBy": "sum"
          },
          {
            "name": " Sales",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "e5ff9a46-7159-4f30-8fec-73efadae0a98",
            "sourceColumn": " Sales",
            "summarizeBy": "sum"
          },
          {
            "name": "COGS",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9c05bd22-dd98-4d13-a738-2a05c0928462",
            "sourceColumn": "COGS",
            "summarizeBy": "sum"
          },
          {
            "name": "Profit",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c5b9c2d7-84da-44bd-9aa0-70aa7af5b8b1",
            "sourceColumn": "Profit",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "13202da1-8f15-492c-a4c7-6785de4f1124",
            "sourceColumn": "Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_c3011088-7384-4d5c-b202-ab45b52fa449"
                },
                "isDefault": true,
                "relationship": "dd1b9b21-4398-475b-a672-8423a7b1d115"
              }
            ]
          },
          {
            "name": "Month Number",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5847cf88-20fc-4c74-ab69-2d16dda63851",
            "sourceColumn": "Month Number",
            "summarizeBy": "sum"
          },
          {
            "name": "Month Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ecae640-d0f6-440c-8a91-64f236d0b557",
            "sourceColumn": "Month Name",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a8bb537b-e3a3-4867-9704-534aa1c107f9",
            "sourceColumn": "Year",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "960268ff-ec78-4a03-bc59-430915e4fc6c",
        "partitions": [
          {
            "name": "financials",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                " Source = Excel.Workbook(File.Contents(\"C:\\Program Files\\WindowsApps\\Microsoft.MicrosoftPowerBIDesktop_2.138.1203.0_x64__8wekyb3d8bbwe\\bin\\SampleData\\Financial Sample.xlsx\"), null, true),",
                "    financials_Table = Source{[Item=\"financials\",Kind=\"Table\"]}[Data],",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(financials_Table,{{\"Segment\", type text}, {\"Country\", type text}, {\"Product\", type text}, {\"Discount Band\", type text}, {\"Units Sold\", type number}, {\"Manufacturing Price\", Int64.Type}, {\"Sale Price\", Int64.Type}, {\"Gross Sales\", type number}, {\"Discounts\", type number}, {\" Sales\", type number}, {\"COGS\", type number}, {\"Profit\", type number}, {\"Date\", type date}, {\"Month Number\", Int64.Type}, {\"Month Name\", type text}, {\"Year\", Int64.Type}})",
                "in",
                " #\"Tipo Alterado\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_4055d9b1-84e5-4b63-9c53-496353a2e0d0",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "db91eea5-8b79-436c-b46f-113a5e83bc9d",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "05407ca0-f033-462b-91a2-0763b0068763",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c6bd0d63-57e0-44be-afa8-5b4cb11a2ce6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ec6ba73c-0bcd-4aef-92ce-9073d9510d96",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "65b15e36-2abd-4118-8180-61b9c8a09944",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9da85b9f-272b-42af-b4e9-51d0d7d47455",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "6a35730c-997c-4ec8-9b98-2ec32320e5b2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d464cc72-a2f5-4c09-8171-d9fe3f051708",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "e9f0a0b7-7b06-4f09-bc7a-330a46e36f23",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "4ab16a31-d340-4fc3-b532-1f4fa5f9d171",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "a9cfbc8f-10d7-47d4-b9ba-20df52065732",
                "ordinal": 3
              }
            ],
            "lineageTag": "92244ee4-1234-456b-98c3-439563c4a9c6"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "a9cca101-cfc4-4358-9ce1-4ba81e5cc43d",
        "partitions": [
          {
            "name": "DateTableTemplate_4055d9b1-84e5-4b63-9c53-496353a2e0d0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_c3011088-7384-4d5c-b202-ab45b52fa449",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "545bf085-af0a-486c-bcb0-326ca9befd66",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5cfaff5c-3dcf-4cf5-a391-2892b23e377f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "74b259be-69b0-467d-8b96-ca09f5e4ce69",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4bf4ec90-caac-4335-8cae-dafb6d5dd383",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1980e6af-747b-402a-bfc0-89dc75b6157c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "385000c3-e24a-4a48-ab44-4da6c876277d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "aba28013-491a-4f1a-85b1-c1a6682d1545",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "726ef89e-35ed-4992-8efc-239930ae0e30",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "d1044c29-fe8a-4cd2-885e-ec414900f122",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "7f8e794d-788f-4be4-9021-fbfc496ea7ab",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "880da523-546e-4f8f-a4cb-912e542c480e",
                "ordinal": 3
              }
            ],
            "lineageTag": "bd491fb0-217a-48ee-8955-4ed3a81d199a"
          }
        ],
        "isHidden": true,
        "lineageTag": "5567c75a-6e0c-4c58-8dd7-17a9e62300dd",
        "partitions": [
          {
            "name": "LocalDateTable_c3011088-7384-4d5c-b202-ab45b52fa449",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('financials'[Date])), 1, 1), Date(Year(MAX('financials'[Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}